"""Tests for the scheduled vulnerability sweep.

The sweep is judged on what it *does not* file, so most of this file is about rejection: an
advisory already filed, one a maintainer closed, one whose fix is a lock refresh, one with no fix
at all. The findings that do get through are asserted on the captured `POST /repos/…/issues` body
rather than on a return value, because the issue is the artefact — its class label picks the
playbook and its body is the whole of what a Devin session is told
(`.claude/rules/testing.md`, "assert the captured request").

OSV and GitHub are `respx` fakes over the real clients. The OSV fake answers `querybatch` from the
request it was sent, so a test that adds a package to the tree gets a truthful answer for it and
one that does not is not silently handed advisories for packages the scanner never asked about.

The manifests are cut down from `taxpon/superset` at the state
`docs/remediation-candidates.md` triaged: the paramiko pin and its two documented blockers, the
deck.gl family reaching `image-size` transitively, and the entries T50 examined and rejected.
"""

from __future__ import annotations

import json
import re
from collections.abc import Mapping, Sequence
from typing import Any

import httpx
import pytest
import respx

from conftest import FakeAPI, make_settings
from sentinel.config import Settings
from sentinel.scanner import audit

REPO = "taxpon/superset"

# --------------------------------------------------------------------------------- the tree

PYPROJECT = """\
[project]
name = "apache-superset"
dependencies = [
    "cryptography>=49.0.0, <50.0.0",
    "flask>=2.2.5, <4.0.0",
    "paramiko>=3.4.0, <4.0", # 4.0 removed DSSKey, still referenced by sshtunnel
    "pgsanity",
    "sqlalchemy>=1.4.43, <2",
]

[project.optional-dependencies]
development = [
    "pytest<10.0.0",
]

[tool.liccheck.authorized_packages]
paramiko = "3"  # GPL
"""

BASE_TXT = """\
# This file is autogenerated by pip-compile.
cryptography==49.0.0
    # via paramiko
flask==2.3.3
    # via apache-superset (pyproject.toml)
paramiko==3.5.1
    # via
    #   apache-superset (pyproject.toml)
    #   sshtunnel
pgsanity==0.2.9
setuptools==80.9.0
sqlalchemy==1.4.54
"""

DEVELOPMENT_TXT = """\
# This file is autogenerated by pip-compile.
flask==2.3.3
paramiko==3.5.1
pip==25.1.1
pytest==7.4.4
"""
"""The development compile carries base's pins too, so a package is pinned in two files at once."""

PACKAGE_JSON = json.dumps(
    {
        "name": "superset",
        "dependencies": {
            "@deck.gl/core": "~9.2.5",
            "@deck.gl/mesh-layers": "~9.2.5",
            "@luma.gl/gltf": "~9.2.5",
            "dompurify": "^3.4.12",
            "xlsx": "https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz",
        },
        "devDependencies": {"jest": "^29.0.0"},
        # A resolution repeats the name and the range further down the file, so the line a
        # declaration is reported at is the first one and not merely "a" matching line.
        "overrides": {"dompurify": "^3.4.12"},
    },
    indent=2,
)

PACKAGE_LOCK = json.dumps(
    {
        "name": "superset",
        "lockfileVersion": 3,
        "packages": {
            "": {
                "name": "superset",
                "dependencies": {
                    "@deck.gl/core": "~9.2.5",
                    "@deck.gl/mesh-layers": "~9.2.5",
                    "@luma.gl/gltf": "~9.2.5",
                    "dompurify": "^3.4.12",
                    "xlsx": "https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz",
                },
                "devDependencies": {"jest": "^29.0.0"},
            },
            "plugins/preset-chart-deckgl": {
                "name": "@superset-ui/plugin-chart-deckgl",
                "version": "0.1.0",
                "dependencies": {"@deck.gl/aggregation-layers": "~9.2.11"},
            },
            "node_modules/@deck.gl/aggregation-layers": {"version": "9.2.11"},
            "node_modules/@deck.gl/core": {"version": "9.2.6"},
            "node_modules/@deck.gl/mesh-layers": {
                "version": "9.2.6",
                "dependencies": {"@luma.gl/gltf": "9.2.6"},
            },
            "node_modules/@luma.gl/gltf": {
                "version": "9.2.6",
                "dependencies": {"@loaders.gl/textures": "^4.3.0"},
            },
            "node_modules/@loaders.gl/textures": {
                "version": "4.3.4",
                "dependencies": {"texture-compressor": "^1.0.2"},
            },
            "node_modules/texture-compressor": {
                "version": "1.0.2",
                "dependencies": {"image-size": "^0.7.4"},
            },
            "node_modules/image-size": {"version": "0.7.5"},
            "node_modules/dompurify": {"version": "3.4.12"},
            "node_modules/jest": {"version": "29.7.0"},
            "node_modules/xlsx": {"version": "0.20.3"},
        },
    },
    indent=2,
)

TREE: Mapping[str, str] = {
    audit.PYPROJECT: PYPROJECT,
    "requirements/base.txt": BASE_TXT,
    "requirements/development.txt": DEVELOPMENT_TXT,
    audit.FRONTEND_PACKAGE_JSON: PACKAGE_JSON,
    audit.FRONTEND_LOCKFILE: PACKAGE_LOCK,
}

PACKAGES_IN_TREE = 18
"""Eight pinned by pip-compile, ten resolved in the lockfile — and not the workspace itself."""


# ------------------------------------------------------------------------------ OSV records

PARAMIKO_GHSA = "GHSA-r374-rxx8-8654"
PARAMIKO_PYSEC = "PYSEC-2026-2858"
PARAMIKO_CVE = "CVE-2026-44405"
IMAGE_SIZE_ICNS = "GHSA-w3rx-r6r6-pgpr"
IMAGE_SIZE_JXL = "GHSA-5p2g-fcmc-qvqq"
DOMPURIFY = "GHSA-55q2-fjhq-7xh7"
XLSX = "GHSA-4r6h-8v6p-xvw6"
SETUPTOOLS = "GHSA-h35f-9h28-mq5c"
FLASK = "GHSA-68rp-wp8r-4726"
CRYPTOGRAPHY = "GHSA-g6cj-pr64-35w5"


def record(
    identifier: str,
    *,
    package: str,
    ecosystem: str = audit.PYPI,
    events: Sequence[Mapping[str, str]] = ({"introduced": "0"}, {"fixed": "9.9.9"}),
    aliases: Sequence[str] = (),
    summary: str = "A vulnerability",
    severity: str | None = "HIGH",
    withdrawn: str | None = None,
    references: Sequence[str] = (),
) -> dict[str, Any]:
    """One `GET /v1/vulns/{id}` body, shaped like the ones `api.osv.dev` actually returns."""
    body: dict[str, Any] = {
        "id": identifier,
        "summary": summary,
        "aliases": list(aliases),
        "affected": [
            {
                "package": {"name": package, "ecosystem": ecosystem},
                "ranges": [{"type": "ECOSYSTEM", "events": list(events)}],
            }
        ],
        "references": [{"type": "WEB", "url": url} for url in references],
    }
    if severity is not None:
        body["database_specific"] = {"severity": severity}
    if withdrawn is not None:
        body["withdrawn"] = withdrawn
    return body


PARAMIKO_RECORD = record(
    PARAMIKO_GHSA,
    package="paramiko",
    aliases=[PARAMIKO_CVE, PARAMIKO_PYSEC],
    summary="Paramiko rsakey.py allows the SHA-1 algorithm",
    severity="LOW",
    # The real advisory closes its range with `last_affected` and never states a fixed version.
    events=({"introduced": "0"}, {"last_affected": "4.0.0"}),
    references=["https://nvd.nist.gov/vuln/detail/CVE-2026-44405"],
)

IMAGE_SIZE_RECORD = record(
    IMAGE_SIZE_ICNS,
    package="image-size",
    ecosystem=audit.NPM,
    summary="image-size: ICNS parser allows denial of service through an infinite loop",
    events=({"introduced": "0"}, {"last_affected": "2.0.2"}),
)


# ---------------------------------------------------------------------------------- fixtures


@pytest.fixture
def osv_api(http_mock: respx.MockRouter) -> FakeAPI:
    return FakeAPI(http_mock, audit.OSV_API_BASE)


@pytest.fixture
def scanner_settings() -> Settings:
    return make_settings(target_repo=REPO, target_base_branch="master")


def serve_tree(github: FakeAPI, tree: Mapping[str, str] = TREE) -> None:
    """Answer the contents endpoint for every manifest the sweep asks for, `404` for the rest."""
    for path in (
        audit.PYPROJECT,
        *audit.REQUIREMENTS,
        audit.FRONTEND_PACKAGE_JSON,
        audit.FRONTEND_LOCKFILE,
    ):
        route = github.route("GET", f"/repos/{REPO}/contents/{path}")
        body = tree.get(path)
        route.mock(
            return_value=httpx.Response(200, text=body)
            if body is not None
            else httpx.Response(404, json={"message": "Not Found"})
        )


def serve_osv(osv: FakeAPI, records: Sequence[Mapping[str, Any]]) -> None:
    """A batch endpoint that answers from the query it was sent, and one record per id."""
    by_package: dict[tuple[str, str], list[str]] = {}
    for entry in records:
        for affected in entry["affected"]:
            key = (affected["package"]["ecosystem"], affected["package"]["name"])
            by_package.setdefault(key, []).append(str(entry["id"]))

    def batch(request: httpx.Request) -> httpx.Response:
        queries = json.loads(request.content)["queries"]
        return httpx.Response(
            200,
            json={
                "results": [
                    {
                        "vulns": [
                            {"id": identifier}
                            for identifier in by_package.get(
                                (query["package"]["ecosystem"], query["package"]["name"]), ()
                            )
                        ]
                    }
                    for query in queries
                ]
            },
        )

    osv.route("POST", "/v1/querybatch").mock(side_effect=batch)
    for entry in records:
        osv.responds("GET", f"/v1/vulns/{entry['id']}", 200, entry)


def serve_issues(github: FakeAPI, issues: Sequence[Mapping[str, Any]] = ()) -> None:
    """Answer the issue list from `issues`, re-read on every request.

    Live rather than fixed, so a test can file into the same list the next run reads back — which
    is the loop the whole idempotence claim rests on.
    """
    github.route("GET", f"/repos/{REPO}/issues").mock(
        side_effect=lambda request: httpx.Response(200, json=list(issues))
    )


def serve_creation(github: FakeAPI, start: int = 4200) -> None:
    counter = iter(range(start, start + 50))

    def created(request: httpx.Request) -> httpx.Response:
        sent = json.loads(request.content)
        number = next(counter)
        return httpx.Response(
            201,
            json={
                "number": number,
                "html_url": f"https://github.com/{REPO}/issues/{number}",
                "title": sent["title"],
                "body": sent["body"],
            },
        )

    github.route("POST", f"/repos/{REPO}/issues").mock(side_effect=created)


def filed_issue(body: str, *, number: int = 1, state: str = "open") -> dict[str, Any]:
    return {
        "number": number,
        "html_url": f"https://github.com/{REPO}/issues/{number}",
        "title": "an earlier finding",
        "body": body,
        "state": state,
    }


async def run_sweep(
    settings: Settings,
    github: FakeAPI,
    osv: FakeAPI,
    *,
    tree: Mapping[str, str] = TREE,
    records: Sequence[Mapping[str, Any]] = (),
    issues: Sequence[Mapping[str, Any]] = (),
) -> audit.SweepReport:
    serve_tree(github, tree)
    serve_osv(osv, records)
    serve_issues(github, issues)
    serve_creation(github)
    async with audit.TargetRepository(settings) as repository, audit.OsvClient() as client:
        return await audit.sweep(tracker=repository, osv=client, settings=settings)


def markers(body: str) -> set[str]:
    return set(re.findall(rf"<!-- {audit.MARKER}: (\S+) -->", body))


# ============================================================================ manifest reading


def test_requirements_pins_carry_their_line_number() -> None:
    pins = audit.parse_requirements("requirements/base.txt", BASE_TXT)

    paramiko = next(pin for pin in pins if pin.name == "paramiko")
    assert paramiko.version == "3.5.1"
    assert paramiko.pinned_at is not None
    assert paramiko.pinned_at.line == 6
    assert paramiko.pinned_at.text == "paramiko==3.5.1"
    assert str(paramiko.pinned_at) == "requirements/base.txt:6"
    # The `# via` continuation lines are comments, not pins.
    assert [pin.name for pin in pins] == [
        "cryptography",
        "flask",
        "paramiko",
        "pgsanity",
        "setuptools",
        "sqlalchemy",
    ]


@pytest.mark.parametrize(
    ("line", "name", "version"),
    [
        ("Flask_Caching==2.1.0", "flask-caching", "2.1.0"),
        ("celery[redis]==5.5.3", "celery", "5.5.3"),
        ("markdown==3.9 ; python_version >= '3.10'", "markdown", "3.9"),
        ("numpy==1.26.4  # pinned for pandas", "numpy", "1.26.4"),
        ("wtforms==3.2.1 \\", "wtforms", "3.2.1"),
    ],
)
def test_a_pin_is_read_past_extras_markers_and_comments(line: str, name: str, version: str) -> None:
    (pin,) = audit.parse_requirements("requirements/base.txt", line)

    assert (pin.name, pin.version) == (name, version)


@pytest.mark.parametrize(
    "line",
    [
        "-r base.txt",
        "--no-binary :all:",
        "# paramiko==3.5.1",
        "flask>=2.2.5",
        "    # via sshtunnel",
    ],
)
def test_only_an_exact_pin_states_an_installed_version(line: str) -> None:
    assert audit.parse_requirements("requirements/base.txt", line) == []


def test_a_python_package_carries_the_constraint_pyproject_declares() -> None:
    resolved = {dep.name: dep for dep in audit.python_dependencies(TREE)}

    paramiko = resolved["paramiko"]
    assert paramiko.constraint == ">=3.4.0, <4.0"
    assert paramiko.declared_at is not None
    assert paramiko.declared_at.path == "pyproject.toml"
    # The declaration's own comment comes with it: the DSSKey note is the first of the two blockers
    # `docs/remediation-candidates.md` names, and it is on this line.
    assert "removed DSSKey" in paramiko.declared_at.text
    # Declared in an optional-dependencies group rather than the main list.
    assert resolved["pytest"].constraint == "<10.0.0"
    # Pinned by pip-compile, declared by nothing.
    assert resolved["setuptools"].declared_at is None
    assert resolved["setuptools"].constraint is None
    # Declared, but as a bare name: the project states where to look and no opinion about versions.
    assert resolved["pgsanity"].declared_at is not None
    assert resolved["pgsanity"].constraint is None


def test_a_package_pinned_in_two_files_is_reported_against_the_first() -> None:
    resolved = {dep.name: dep for dep in audit.python_dependencies(TREE)}

    # `flask` and `paramiko` are pinned in both compile outputs at the same version. One installed
    # package, and the issue should send a reader to the manifest they would open first.
    assert resolved["flask"].pinned_at is not None
    assert resolved["flask"].pinned_at.path == "requirements/base.txt"
    assert resolved["paramiko"].pinned_at is not None
    assert resolved["paramiko"].pinned_at.line == 6
    assert len([dep for dep in audit.python_dependencies(TREE) if dep.name == "flask"]) == 1


def test_a_transitive_npm_package_is_attributed_to_the_dependency_that_pulls_it_in() -> None:
    resolved = {dep.name: dep for dep in audit.npm_dependencies(TREE)}

    image_size = resolved["image-size"]
    assert image_size.version == "0.7.5"
    assert image_size.declared_at is None, "nothing declares image-size"
    assert image_size.chain == (
        "@luma.gl/gltf",
        "@loaders.gl/textures",
        "texture-compressor",
        "image-size",
    )
    assert image_size.entry_at is not None
    assert str(image_size.entry_at) == "superset-frontend/package.json:6"
    assert image_size.entry_at.text == '"@luma.gl/gltf": "~9.2.5",'
    assert image_size.manifest_line is image_size.entry_at


def test_a_declared_npm_package_carries_its_own_range() -> None:
    resolved = {dep.name: dep for dep in audit.npm_dependencies(TREE)}

    assert resolved["dompurify"].constraint == "^3.4.12"
    assert resolved["dompurify"].chain == ()
    assert resolved["dompurify"].declared_at is not None
    # The `dependencies` entry, not the `overrides` repetition further down the same file.
    assert resolved["dompurify"].declared_at.line == 7
    # A devDependency is declared as much as a dependency is.
    assert resolved["jest"].constraint == "^29.0.0"
    assert resolved["jest"].declared_at is not None
    assert resolved["jest"].declared_at.line == 11
    assert resolved["@deck.gl/mesh-layers"].constraint == "~9.2.5"
    # A workspace manifest declares it; the lockfile names the file but not a line in it.
    aggregation = resolved["@deck.gl/aggregation-layers"]
    assert aggregation.declared_at is not None
    assert aggregation.declared_at.path == (
        "superset-frontend/plugins/preset-chart-deckgl/package.json"
    )
    assert aggregation.declared_at.line is None
    assert str(aggregation.declared_at) == aggregation.declared_at.path


def test_the_workspace_package_itself_is_not_an_installed_dependency() -> None:
    names = {dep.name for dep in audit.npm_dependencies(TREE)}

    assert "@superset-ui/plugin-chart-deckgl" not in names
    assert "image-size" in names


def test_a_manifest_that_is_absent_does_not_stop_the_others() -> None:
    resolved = audit.dependencies({audit.PYPROJECT: PYPROJECT, "requirements/base.txt": BASE_TXT})

    assert {dep.name for dep in resolved} >= {"paramiko", "flask"}
    assert all(dep.ecosystem == audit.PYPI for dep in resolved)


# ================================================================================== versions


@pytest.mark.parametrize(
    ("version", "expected"),
    [
        ("3.5.1", (3, 5, 1)),
        ("v2.0", (2, 0)),
        ("1.0.0-beta.2", (1, 0, 0)),
        ("4.3.0+local", (4, 3, 0)),
        ("not-a-version", ()),
    ],
)
def test_release_reads_the_numeric_components(version: str, expected: tuple[int, ...]) -> None:
    assert audit.release(version) == expected


@pytest.mark.parametrize(
    ("version", "expected"),
    [("3.5.1", (3,)), ("0.7.5", (0, 7)), ("0.0.3", (0, 0)), ("12.1", (12,))],
)
def test_below_one_the_minor_is_the_component_that_cannot_move(
    version: str, expected: tuple[int, ...]
) -> None:
    assert audit.significant(version) == expected


@pytest.mark.parametrize(
    ("constraint", "ecosystem", "version", "expected"),
    [
        (">=3.4.0, <4.0", audit.PYPI, "5.0.0", False),
        (">=3.4.0, <4.0", audit.PYPI, "3.9.1", True),
        (">=2.2.5, <4.0.0", audit.PYPI, "3.1.3", True),
        (">=49.0.0, <50.0.0", audit.PYPI, "50.0.0", False),
        ("<10.0.0", audit.PYPI, "9.0.3", True),
        ("~=3.4.1", audit.PYPI, "3.4.9", True),
        ("~=3.4.1", audit.PYPI, "3.5.0", False),
        ("^3.4.12", audit.NPM, "3.4.13", True),
        # A caret admits the rest of the major; a tilde would stop at 3.5.
        ("^3.4.12", audit.NPM, "3.9.0", True),
        ("^3.4.12", audit.NPM, "4.0.0", False),
        ("^0.7.5", audit.NPM, "0.7.9", True),
        ("^0.7.5", audit.NPM, "0.8.0", False),
        ("~9.2.5", audit.NPM, "9.2.11", True),
        ("~9.2.5", audit.NPM, "9.3.0", False),
        ("9.2.6", audit.NPM, "9.2.6", True),
        (">=1.0.0 <3.0.0", audit.NPM, "2.4.0", True),
        # Nothing to read: a CDN tarball, a workspace protocol, a wildcard, a bad number.
        ("https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz", audit.NPM, "0.20.4", None),
        ("workspace:*", audit.NPM, "1.0.0", None),
        ("*", audit.NPM, "1.0.0", None),
        ("~=3", audit.PYPI, "3.1", None),
        ("== whatever", audit.PYPI, "1.0", None),
    ],
)
def test_admits_reads_the_ranges_the_manifests_actually_use(
    constraint: str, ecosystem: str, version: str, expected: bool | None
) -> None:
    assert audit.admits(constraint, ecosystem, version) is expected


# ================================================================================= advisories


def test_the_fix_is_the_nearest_release_above_what_is_installed() -> None:
    parsed = audit.parse_advisory(
        record(
            "GHSA-branchy",
            package="flask",
            events=(
                {"introduced": "0"},
                {"fixed": "2.2.6"},
                {"introduced": "2.3.0"},
                {"fixed": "2.3.9"},
                {"introduced": "3.0.0"},
                {"fixed": "3.1.3"},
            ),
        ),
        {(audit.PYPI, "flask"): "2.3.3"},
    )

    assert parsed.affected[(audit.PYPI, "flask")] == ("2.3.9", None)


def test_an_advisory_that_states_only_a_last_affected_version_keeps_it() -> None:
    parsed = audit.parse_advisory(PARAMIKO_RECORD, {(audit.PYPI, "paramiko"): "3.5.1"})

    assert parsed.affected[(audit.PYPI, "paramiko")] == (None, "4.0.0")
    assert parsed.severity == "LOW"
    assert parsed.identifiers == frozenset({PARAMIKO_GHSA, PARAMIKO_CVE, PARAMIKO_PYSEC})
    assert parsed.id == PARAMIKO_GHSA, "the GHSA is what a maintainer will search for"


def test_a_withdrawn_record_says_so() -> None:
    live = audit.parse_advisory(record("GHSA-live", package="paramiko"), {})
    pulled = audit.parse_advisory(
        record("GHSA-pulled", package="paramiko", withdrawn="2026-03-01T00:00:00Z"), {}
    )

    assert live.withdrawn is False
    assert pulled.withdrawn is True


def test_a_package_that_is_not_installed_is_not_a_finding() -> None:
    parsed = audit.parse_advisory(
        record("GHSA-elsewhere", package="django"), {(audit.PYPI, "paramiko"): "3.5.1"}
    )

    assert parsed.affected == {}


def test_the_same_advisory_published_twice_is_one_advisory() -> None:
    installed = {(audit.PYPI, "paramiko"): "3.5.1"}
    pysec = record(
        PARAMIKO_PYSEC,
        package="paramiko",
        aliases=[PARAMIKO_CVE, PARAMIKO_GHSA],
        severity=None,
        events=({"introduced": "0"}, {"fixed": "5.0.0"}),
    )

    merged = audit._merge(
        audit.parse_advisory(entry, installed) for entry in (PARAMIKO_RECORD, pysec)
    )

    assert len(merged) == 1
    assert merged[0].id == PARAMIKO_GHSA
    assert merged[0].severity == "LOW", (
        "the record that stated a severity wins over the one that did not"
    )
    # The GHSA record has no `fixed` event; the PYSEC one does, and the fix is the better evidence.
    assert merged[0].affected[(audit.PYPI, "paramiko")] == ("5.0.0", "4.0.0")


def test_the_distro_qualifier_on_an_ecosystem_is_not_part_of_the_name() -> None:
    entry = record("GHSA-distro", package="paramiko")
    entry["affected"][0]["package"]["ecosystem"] = "PyPI:2020"

    parsed = audit.parse_advisory(entry, {(audit.PYPI, "paramiko"): "3.5.1"})

    assert (audit.PYPI, "paramiko") in parsed.affected


def test_a_pypi_name_is_matched_after_normalisation() -> None:
    parsed = audit.parse_advisory(
        record("GHSA-underscored", package="Flask_Caching"),
        {(audit.PYPI, "flask-caching"): "2.1.0"},
    )

    assert (audit.PYPI, "flask-caching") in parsed.affected


# ====================================================================================== triage


def finding(
    *,
    name: str = "paramiko",
    ecosystem: str = audit.PYPI,
    version: str = "3.5.1",
    constraint: str | None = None,
    fixed: str | None = "5.0.0",
    last_affected: str | None = None,
    identifier: str = "GHSA-example",
    aliases: Sequence[str] = (),
    severity: str = "HIGH",
    withdrawn: bool = False,
    manifest: bool = True,
) -> audit.Finding:
    line = audit.SourceLine("requirements/base.txt", 1, f"{name}=={version}") if manifest else None
    dependency = audit.Dependency(
        ecosystem=ecosystem,
        name=name,
        version=version,
        pinned_at=line,
        declared_at=audit.SourceLine("pyproject.toml", 9, f'"{name}{constraint}"')
        if constraint
        else None,
        constraint=constraint,
    )
    advisory = audit.Advisory(
        id=identifier,
        identifiers=frozenset({identifier, *aliases}),
        summary="A vulnerability",
        severity=severity,
        withdrawn=withdrawn,
        references=(),
        affected={(ecosystem, name): (fixed, last_affected)},
    )
    return audit.Finding(dependency, advisory, fixed, last_affected)


def reasons(decided: audit.Triage) -> dict[str, audit.Rejected]:
    return {entry.finding.advisory.id: entry.reason for entry in decided.skipped}


@pytest.mark.parametrize(
    ("case", "expected"),
    [
        # The declared range already permits the fix: nothing in the manifest changes.
        (
            {
                "name": "flask",
                "version": "2.3.3",
                "constraint": ">=2.2.5, <4.0.0",
                "fixed": "3.1.3",
            },
            audit.Rejected.LOCK_REFRESH,
        ),
        # The declared range refuses it: the cap has to be renegotiated.
        (
            {
                "name": "paramiko",
                "version": "3.5.1",
                "constraint": ">=3.4.0, <4.0",
                "fixed": "5.0.0",
            },
            None,
        ),
        (
            {
                "name": "cryptography",
                "version": "49.0.0",
                "constraint": ">=49.0.0, <50.0.0",
                "fixed": "50.0.0",
            },
            None,
        ),
        # Nothing declares it, and the fix stays inside the major.
        ({"name": "js-yaml", "version": "4.3.0", "fixed": "4.3.1"}, audit.Rejected.LOCK_REFRESH),
        # Nothing declares it, and the fix crosses the major.
        ({"name": "image-size", "version": "0.7.5", "fixed": "1.2.1"}, None),
        # Below 1.0 the minor is the boundary.
        (
            {"name": "python-multipart", "version": "0.0.29", "fixed": "0.0.30"},
            audit.Rejected.LOCK_REFRESH,
        ),
        ({"name": "python-multipart", "version": "0.0.29", "fixed": "0.1.0"}, None),
        # An unreadable range falls through to the boundary rather than being read as permission.
        (
            {
                "name": "xlsx",
                "version": "0.20.3",
                "constraint": "https://cdn.example/x.tgz",
                "fixed": "0.20.4",
            },
            audit.Rejected.LOCK_REFRESH,
        ),
        # Only a last-affected bound: the fix is above it, so the boundary is read from that.
        (
            {"name": "paramiko", "version": "3.5.1", "fixed": None, "last_affected": "4.0.0"},
            None,
        ),
        (
            {"name": "mcp", "version": "1.24.0", "fixed": None, "last_affected": "1.27.2"},
            audit.Rejected.LOCK_REFRESH,
        ),
    ],
)
def test_only_a_fix_that_forces_a_decision_is_filed(
    case: dict[str, Any], expected: audit.Rejected | None
) -> None:
    decided = audit.triage([finding(**case)], already_filed=frozenset())

    if expected is None:
        assert [candidate.finding.dependency.name for candidate in decided.file] == [case["name"]]
        assert decided.skipped == ()
    else:
        assert decided.file == ()
        assert [entry.reason for entry in decided.skipped] == [expected]


def test_an_advisory_with_no_fix_at_all_is_not_filed() -> None:
    decided = audit.triage(
        [finding(name="xlsx", ecosystem=audit.NPM, fixed=None, last_affected=None)],
        already_filed=frozenset(),
    )

    assert decided.file == ()
    (entry,) = decided.skipped
    assert entry.reason is audit.Rejected.NO_REMEDIATION
    assert "no version constraint that satisfies" in entry.detail


def test_a_suppressed_advisory_carries_its_recorded_justification() -> None:
    decided = audit.triage(
        [
            finding(
                name="xlsx",
                ecosystem=audit.NPM,
                version="0.20.3",
                identifier=XLSX,
                fixed="0.20.4",
            )
        ],
        already_filed=frozenset(),
    )

    assert decided.file == ()
    (entry,) = decided.skipped
    assert entry.reason is audit.Rejected.SUPPRESSED
    assert "abandoned" in entry.detail and "SheetJS CDN" in entry.detail


def test_the_suppression_list_matches_on_an_alias_too() -> None:
    decided = audit.triage(
        [
            finding(
                name="xlsx",
                ecosystem=audit.NPM,
                identifier="CVE-2023-30533",
                aliases=[XLSX],
                fixed="0.20.4",
            )
        ],
        already_filed=frozenset(),
    )

    assert [entry.reason for entry in decided.skipped] == [audit.Rejected.SUPPRESSED]


@pytest.mark.parametrize("name", sorted(audit.BUILD_TOOLCHAIN))
def test_the_packaging_toolchain_is_not_application_dependency_surface(name: str) -> None:
    decided = audit.triage(
        [finding(name=name, version="25.1.1", fixed="26.1")], already_filed=frozenset()
    )

    assert decided.file == ()
    (entry,) = decided.skipped
    assert entry.reason is audit.Rejected.TOOLCHAIN
    assert "no call site to adapt" in entry.detail


def test_a_withdrawn_advisory_is_not_filed() -> None:
    decided = audit.triage([finding(withdrawn=True)], already_filed=frozenset())

    assert [entry.reason for entry in decided.skipped] == [audit.Rejected.WITHDRAWN]


def test_a_package_no_manifest_names_cannot_be_acted_on() -> None:
    decided = audit.triage([finding(manifest=False)], already_filed=frozenset())

    assert decided.file == ()
    (entry,) = decided.skipped
    assert entry.reason is audit.Rejected.UNREACHABLE


def test_a_previously_filed_advisory_is_recognised_by_any_of_its_identifiers() -> None:
    candidate = finding(identifier=PARAMIKO_GHSA, aliases=[PARAMIKO_PYSEC, PARAMIKO_CVE])

    decided = audit.triage(
        [candidate], already_filed=frozenset({(audit.PYPI, "paramiko", PARAMIKO_PYSEC)})
    )

    assert decided.file == ()
    (entry,) = decided.skipped
    assert entry.reason is audit.Rejected.ALREADY_FILED


def test_the_same_advisory_against_a_different_package_is_not_a_duplicate() -> None:
    decided = audit.triage(
        [finding(name="paramiko", identifier="GHSA-shared")],
        already_filed=frozenset({(audit.PYPI, "cryptography", "GHSA-shared")}),
    )

    assert len(decided.file) == 1


def test_two_advisories_on_one_package_become_one_issue() -> None:
    decided = audit.triage(
        [
            finding(
                name="image-size",
                ecosystem=audit.NPM,
                version="0.7.5",
                identifier=IMAGE_SIZE_JXL,
                fixed="2.1.0",
            ),
            finding(
                name="image-size",
                ecosystem=audit.NPM,
                version="0.7.5",
                identifier=IMAGE_SIZE_ICNS,
                fixed="2.1.0",
            ),
        ],
        already_filed=frozenset(),
    )

    (candidate,) = decided.file
    assert candidate.finding.advisory.id == IMAGE_SIZE_JXL
    assert [entry.advisory.id for entry in candidate.also] == [IMAGE_SIZE_ICNS]
    assert set(candidate.fingerprints) == {
        f"npm/image-size/{IMAGE_SIZE_JXL}",
        f"npm/image-size/{IMAGE_SIZE_ICNS}",
    }
    assert decided.skipped == (), "the sibling is covered, not rejected"


def test_the_most_severe_advisory_leads_and_the_rest_wait() -> None:
    candidates = [
        finding(name="low", severity="LOW", identifier="GHSA-low", fixed="9.0.0"),
        finding(name="critical", severity="CRITICAL", identifier="GHSA-crit", fixed="9.0.0"),
        finding(name="moderate", severity="MODERATE", identifier="GHSA-mod", fixed="9.0.0"),
        finding(name="high", severity="HIGH", identifier="GHSA-high", fixed="9.0.0"),
        finding(name="unrated", severity="UNKNOWN", identifier="GHSA-none", fixed="9.0.0"),
    ]

    decided = audit.triage(candidates, already_filed=frozenset())

    assert [candidate.finding.dependency.name for candidate in decided.file] == [
        "critical",
        "high",
        "moderate",
    ]
    assert len(decided.file) == audit.MAX_ISSUES_PER_SWEEP
    over = {entry.finding.dependency.name: entry.reason for entry in decided.skipped}
    assert over == {"low": audit.Rejected.OVER_LIMIT, "unrated": audit.Rejected.OVER_LIMIT}


# =================================================================================== the issue


def test_the_issue_body_carries_everything_a_remediation_needs() -> None:
    candidate = audit.Candidate(
        audit.Finding(
            audit.Dependency(
                ecosystem=audit.PYPI,
                name="paramiko",
                version="3.5.1",
                pinned_at=audit.SourceLine("requirements/base.txt", 283, "paramiko==3.5.1"),
                declared_at=audit.SourceLine(
                    "pyproject.toml", 99, '"paramiko>=3.4.0, <4.0", # 4.0 removed DSSKey'
                ),
                constraint=">=3.4.0, <4.0",
            ),
            audit.parse_advisory(PARAMIKO_RECORD, {(audit.PYPI, "paramiko"): "3.5.1"}),
            None,
            "4.0.0",
        )
    )

    body = audit.issue_body(candidate, repo=REPO)

    assert PARAMIKO_GHSA in body
    assert PARAMIKO_CVE in body and PARAMIKO_PYSEC in body
    assert "Paramiko rsakey.py allows the SHA-1 algorithm" in body
    assert "`requirements/base.txt:283` — `paramiko==3.5.1`" in body
    assert "`pyproject.toml:99`" in body and "removed DSSKey" in body
    assert "| Installed | `3.5.1` |" in body
    assert "| Severity | Low |" in body
    assert "What a regression test must assert" in body
    assert "tests/unit_tests/**" in body
    # The caveat `docs/remediation-candidates.md` insisted on: OSV never stated the fixed version.
    assert "| Fixed in | _not stated by OSV_ |" in body
    assert "The fixed version is not published." in body
    assert "`last_affected: 4.0.0`" in body
    # Why it survived triage, and how to say it should not have.
    assert "outside `>=3.4.0, <4.0`" in body
    assert "report `outcome: blocked`" in body
    # Reproducible by anyone reading the issue.
    assert "api.osv.dev/v1/querybatch" in body
    assert markers(body) == {f"PyPI/paramiko/{PARAMIKO_GHSA}"}


def test_a_transitive_finding_names_the_dependency_that_has_to_move() -> None:
    dependency = next(dep for dep in audit.npm_dependencies(TREE) if dep.name == "image-size")
    candidate = audit.Candidate(
        audit.Finding(
            dependency,
            audit.parse_advisory(IMAGE_SIZE_RECORD, {(audit.NPM, "image-size"): "0.7.5"}),
            None,
            "2.0.2",
        )
    )

    body = audit.issue_body(candidate, repo=REPO)

    assert "Reached from" in body
    assert "`superset-frontend/package.json:6`" in body
    assert '`"@luma.gl/gltf": "~9.2.5",`' in body
    assert "`@luma.gl/gltf` → `@loaders.gl/textures` → `texture-compressor` → `image-size`" in body
    assert "Pinned at" not in body, "no line of a lockfile is edited by hand"
    assert "scoped jest run" in body


def test_a_grouped_issue_lists_the_siblings_and_claims_their_fingerprints() -> None:
    primary = finding(
        name="image-size",
        ecosystem=audit.NPM,
        version="0.7.5",
        identifier=IMAGE_SIZE_JXL,
        fixed="2.1.0",
    )
    sibling = finding(
        name="image-size",
        ecosystem=audit.NPM,
        version="0.7.5",
        identifier=IMAGE_SIZE_ICNS,
        fixed=None,
        last_affected="2.0.2",
    )

    body = audit.issue_body(audit.Candidate(primary, (sibling,)), repo=REPO)

    assert "## Also on `image-size`" in body
    assert IMAGE_SIZE_ICNS in body
    assert "One upgrade answers all of them" in body
    assert markers(body) == {
        f"npm/image-size/{IMAGE_SIZE_JXL}",
        f"npm/image-size/{IMAGE_SIZE_ICNS}",
    }


@pytest.mark.parametrize(
    ("constraint", "expected"),
    [
        # The declared range refused the fix, and saying so tells a reader what to renegotiate.
        (">=3.4.0, <4.0", "The fix is outside `>=3.4.0, <4.0`"),
        # A range this module cannot read decided nothing; the version boundary did.
        ("https://cdn.example/x.tgz", "No range the repository declares"),
        (None, "No range the repository declares"),
    ],
)
def test_the_issue_says_which_rule_filed_it(constraint: str | None, expected: str) -> None:
    body = audit.issue_body(
        audit.Candidate(finding(constraint=constraint, fixed="5.0.0")), repo=REPO
    )

    assert expected in body
    assert "outside ``" not in body, "a package declared as a bare name has no range to quote"


def test_the_title_names_the_class_the_package_and_the_advisory() -> None:
    candidate = audit.Candidate(finding(identifier=PARAMIKO_GHSA))

    assert (
        audit.issue_title(candidate)
        == f"security-dep: paramiko 3.5.1 is affected by {PARAMIKO_GHSA}"
    )


@pytest.mark.parametrize(
    ("ecosystem", "expected"),
    [(audit.PYPI, "class:security-dep"), (audit.NPM, "class:frontend-dep")],
)
def test_the_ecosystem_selects_the_class_label(
    ecosystem: str, expected: str, scanner_settings: Settings
) -> None:
    candidate = audit.Candidate(finding(ecosystem=ecosystem))

    assert audit.issue_labels(candidate, scanner_settings) == ("devin:autofix", expected)


def test_the_trigger_label_follows_configuration() -> None:
    settings = make_settings(autofix_label="bot:fix")

    assert audit.issue_labels(audit.Candidate(finding()), settings)[0] == "bot:fix"


def test_a_fingerprint_is_read_back_off_a_body_the_sweep_wrote() -> None:
    body = audit.issue_body(audit.Candidate(finding(identifier=PARAMIKO_GHSA)), repo=REPO)

    assert audit.filed_fingerprints([audit.FiledIssue(1, "u", "t", body)]) == frozenset(
        {(audit.PYPI, "paramiko", PARAMIKO_GHSA)}
    )


def test_an_issue_nobody_fingerprinted_tracks_nothing() -> None:
    assert audit.filed_fingerprints([audit.FiledIssue(1, "u", "t", "please bump paramiko")]) == (
        frozenset()
    )


# ================================================================================ the GitHub API


async def test_a_missing_manifest_is_an_answer_rather_than_a_failure(
    scanner_settings: Settings, github_api: FakeAPI
) -> None:
    github_api.responds("GET", f"/repos/{REPO}/contents/requirements/base.txt", 404, {})

    async with audit.TargetRepository(scanner_settings) as repository:
        assert await repository.read("requirements/base.txt") is None


async def test_a_manifest_is_read_from_the_targets_default_branch(
    scanner_settings: Settings, github_api: FakeAPI
) -> None:
    github_api.route("GET", f"/repos/{REPO}/contents/pyproject.toml").mock(
        return_value=httpx.Response(200, text=PYPROJECT)
    )

    async with audit.TargetRepository(scanner_settings) as repository:
        assert await repository.read("pyproject.toml") == PYPROJECT

    sent = github_api.only("GET", f"/repos/{REPO}/contents/pyproject.toml")
    assert sent.url.params["ref"] == "master"
    assert sent.headers["accept"] == "application/vnd.github.raw"


async def test_a_manifest_that_cannot_be_read_stops_the_sweep(
    scanner_settings: Settings, github_api: FakeAPI
) -> None:
    github_api.responds("GET", f"/repos/{REPO}/contents/pyproject.toml", 500, {})

    async with audit.TargetRepository(scanner_settings) as repository:
        with pytest.raises(audit.ScannerError, match="500"):
            await repository.read("pyproject.toml")


async def test_the_sweep_reads_closed_issues_as_well_as_open_ones(
    scanner_settings: Settings, github_api: FakeAPI
) -> None:
    serve_issues(github_api, [filed_issue("<!-- sentinel-advisory: PyPI/paramiko/X -->")])

    async with audit.TargetRepository(scanner_settings) as repository:
        issues = await repository.list_issues("class:security-dep")

    assert [issue.number for issue in issues] == [1]
    sent = github_api.only("GET", f"/repos/{REPO}/issues")
    assert sent.url.params["state"] == "all"
    assert sent.url.params["labels"] == "class:security-dep"


async def test_a_pull_request_is_not_an_issue(
    scanner_settings: Settings, github_api: FakeAPI
) -> None:
    serve_issues(
        github_api,
        [
            filed_issue("body", number=1),
            {**filed_issue("body", number=2), "pull_request": {"url": "…"}},
        ],
    )

    async with audit.TargetRepository(scanner_settings) as repository:
        issues = await repository.list_issues("class:security-dep")

    assert [issue.number for issue in issues] == [1]


async def test_every_page_of_the_issue_list_is_read(
    scanner_settings: Settings, github_api: FakeAPI
) -> None:
    second = f"{audit.GITHUB_API_BASE}/repos/{REPO}/issues?page=2"
    github_api.route("GET", f"/repos/{REPO}/issues").mock(
        side_effect=[
            httpx.Response(
                200, json=[filed_issue("a", number=1)], headers={"Link": f'<{second}>; rel="next"'}
            ),
            httpx.Response(200, json=[filed_issue("b", number=2)]),
        ]
    )

    async with audit.TargetRepository(scanner_settings) as repository:
        issues = await repository.list_issues("class:security-dep")

    assert [issue.number for issue in issues] == [1, 2]


async def test_creating_an_issue_sends_the_title_body_and_labels(
    scanner_settings: Settings, github_api: FakeAPI
) -> None:
    serve_creation(github_api)

    async with audit.TargetRepository(scanner_settings) as repository:
        issue = await repository.create_issue(
            title="t", body="b", labels=("devin:autofix", "class:security-dep")
        )

    assert issue.number == 4200
    sent = github_api.only("POST", f"/repos/{REPO}/issues")
    assert sent.json == {
        "title": "t",
        "body": "b",
        "labels": ["devin:autofix", "class:security-dep"],
    }


async def test_a_refused_issue_is_not_reported_as_filed(
    scanner_settings: Settings, github_api: FakeAPI
) -> None:
    github_api.responds("POST", f"/repos/{REPO}/issues", 422, {"message": "Validation Failed"})

    async with audit.TargetRepository(scanner_settings) as repository:
        with pytest.raises(audit.ScannerError, match="422"):
            await repository.create_issue(title="t", body="b", labels=("devin:autofix",))


async def test_the_repr_does_not_carry_the_token(scanner_settings: Settings) -> None:
    async with audit.TargetRepository(scanner_settings) as repository:
        assert repr(repository) == f"TargetRepository(repo='{REPO}')"


# ===================================================================================== the OSV API


async def test_the_whole_tree_is_queried_in_batches(osv_api: FakeAPI) -> None:
    packages = [
        audit.Dependency(ecosystem=audit.NPM, name=f"p{index}", version="1.0.0")
        for index in range(audit.QUERY_BATCH_SIZE + 3)
    ]
    serve_osv(osv_api, [])

    async with audit.OsvClient() as client:
        assert await client.advisories(packages) == []

    batches = osv_api.sent("POST", "/v1/querybatch")
    assert [len(batch.json["queries"]) for batch in batches] == [audit.QUERY_BATCH_SIZE, 3]
    assert batches[0].json["queries"][0] == {
        "package": {"name": "p0", "ecosystem": "npm"},
        "version": "1.0.0",
    }


async def test_an_advisory_named_by_two_packages_is_fetched_once(osv_api: FakeAPI) -> None:
    shared = record("GHSA-shared", package="paramiko")
    shared["affected"].append(
        {
            "package": {"name": "flask", "ecosystem": audit.PYPI},
            "ranges": [{"type": "ECOSYSTEM", "events": [{"introduced": "0"}, {"fixed": "9.9.9"}]}],
        }
    )
    serve_osv(osv_api, [shared])

    async with audit.OsvClient() as client:
        advisories = await client.advisories(
            [
                audit.Dependency(ecosystem=audit.PYPI, name="paramiko", version="3.5.1"),
                audit.Dependency(ecosystem=audit.PYPI, name="flask", version="2.3.3"),
            ]
        )

    assert len(osv_api.sent("GET", "/v1/vulns/GHSA-shared")) == 1
    assert len(advisories) == 1
    assert set(advisories[0].affected) == {(audit.PYPI, "paramiko"), (audit.PYPI, "flask")}


async def test_an_osv_failure_is_a_scanner_error(osv_api: FakeAPI) -> None:
    osv_api.responds("POST", "/v1/querybatch", 503, {})

    async with audit.OsvClient() as client:
        with pytest.raises(audit.ScannerError, match="querybatch"):
            await client.advisories(
                [audit.Dependency(ecosystem=audit.PYPI, name="paramiko", version="3.5.1")]
            )


# ======================================================================================= the sweep


ALL_RECORDS = [
    PARAMIKO_RECORD,
    IMAGE_SIZE_RECORD,
    record(
        IMAGE_SIZE_JXL,
        package="image-size",
        ecosystem=audit.NPM,
        events=({"introduced": "0"}, {"last_affected": "2.0.2"}),
    ),
    record(
        DOMPURIFY,
        package="dompurify",
        ecosystem=audit.NPM,
        events=({"introduced": "0"}, {"fixed": "3.4.13"}),
    ),
    record(XLSX, package="xlsx", ecosystem=audit.NPM, events=({"introduced": "0"},)),
    record(SETUPTOOLS, package="setuptools", events=({"introduced": "0"}, {"fixed": "83.0.0"})),
    record(
        FLASK, package="flask", events=({"introduced": "0"}, {"fixed": "3.1.3"}), severity="LOW"
    ),
]


async def test_the_sweep_files_the_findings_that_force_a_decision_and_nothing_else(
    scanner_settings: Settings, github_api: FakeAPI, osv_api: FakeAPI
) -> None:
    report = await run_sweep(scanner_settings, github_api, osv_api, records=ALL_RECORDS)

    assert [issue.title for issue in report.filed] == [
        f"frontend-dep: image-size 0.7.5 is affected by {IMAGE_SIZE_JXL}",
        f"security-dep: paramiko 3.5.1 is affected by {PARAMIKO_GHSA}",
    ]
    assert report.by_reason == {
        audit.Rejected.SUPPRESSED: 1,  # xlsx, unsatisfiable and recorded as such
        audit.Rejected.TOOLCHAIN: 1,  # setuptools, no call site
        audit.Rejected.LOCK_REFRESH: 2,  # flask inside its range, dompurify inside its major
    }
    assert report.scanned == PACKAGES_IN_TREE


async def test_the_filed_issue_is_labelled_for_its_playbook(
    scanner_settings: Settings, github_api: FakeAPI, osv_api: FakeAPI
) -> None:
    await run_sweep(scanner_settings, github_api, osv_api, records=ALL_RECORDS)

    sent = {
        request.json["title"]: request.json
        for request in github_api.sent("POST", f"/repos/{REPO}/issues")
    }
    frontend = sent[f"frontend-dep: image-size 0.7.5 is affected by {IMAGE_SIZE_JXL}"]
    backend = sent[f"security-dep: paramiko 3.5.1 is affected by {PARAMIKO_GHSA}"]

    assert frontend["labels"] == ["devin:autofix", "class:frontend-dep"]
    assert backend["labels"] == ["devin:autofix", "class:security-dep"]
    assert "`requirements/base.txt:6` — `paramiko==3.5.1`" in backend["body"]
    assert "`superset-frontend/package.json:6`" in frontend["body"]
    # Both advisories on image-size are answered by the one issue.
    assert markers(frontend["body"]) == {
        f"npm/image-size/{IMAGE_SIZE_ICNS}",
        f"npm/image-size/{IMAGE_SIZE_JXL}",
    }


async def test_a_second_run_over_an_unchanged_tree_files_nothing(
    scanner_settings: Settings, github_api: FakeAPI, osv_api: FakeAPI
) -> None:
    """The property the whole design turns on, exercised as the schedule exercises it.

    The issue list the second run reads is the one the first run wrote into, so nothing about the
    recognition is arranged by the test: if the fingerprint the sweep writes and the fingerprint it
    looks for ever stop being the same string, this fails.
    """
    on_the_repo: list[dict[str, Any]] = []
    serve_tree(github_api)
    serve_osv(osv_api, ALL_RECORDS)
    serve_issues(github_api, on_the_repo)
    serve_creation(github_api)

    async with audit.TargetRepository(scanner_settings) as repository, audit.OsvClient() as osv:
        first = await audit.sweep(tracker=repository, osv=osv, settings=scanner_settings)
        on_the_repo += [
            filed_issue(issue.body, number=issue.number, state="open") for issue in first.filed
        ]
        second = await audit.sweep(tracker=repository, osv=osv, settings=scanner_settings)

    assert len(first.filed) == 2
    assert second.filed == ()
    assert len(github_api.sent("POST", f"/repos/{REPO}/issues")) == 2, "no second attempt"
    assert second.by_reason[audit.Rejected.ALREADY_FILED] == 3, (
        "paramiko, and both image-size advisories, recognised from the two issues filed"
    )


async def test_an_issue_a_maintainer_closed_is_not_filed_again(
    scanner_settings: Settings, github_api: FakeAPI, osv_api: FakeAPI
) -> None:
    closed = filed_issue(
        f"<!-- {audit.MARKER}: PyPI/paramiko/{PARAMIKO_GHSA} -->", number=7, state="closed"
    )

    report = await run_sweep(
        scanner_settings, github_api, osv_api, records=[PARAMIKO_RECORD], issues=[closed]
    )

    assert report.filed == ()
    assert report.by_reason == {audit.Rejected.ALREADY_FILED: 1}


async def test_an_advisory_filed_under_an_older_identifier_is_still_recognised(
    scanner_settings: Settings, github_api: FakeAPI, osv_api: FakeAPI
) -> None:
    # Filed on a night when OSV answered only with the PYSEC record; the GHSA has since appeared
    # and is now the preferred id.
    earlier = filed_issue(f"<!-- {audit.MARKER}: PyPI/paramiko/{PARAMIKO_PYSEC} -->")

    report = await run_sweep(
        scanner_settings, github_api, osv_api, records=[PARAMIKO_RECORD], issues=[earlier]
    )

    assert report.filed == ()
    assert report.by_reason == {audit.Rejected.ALREADY_FILED: 1}


async def test_the_sweep_asks_for_both_of_the_labels_it_files_under(
    scanner_settings: Settings, github_api: FakeAPI, osv_api: FakeAPI
) -> None:
    await run_sweep(scanner_settings, github_api, osv_api, records=[PARAMIKO_RECORD])

    asked = {
        request.url.params["labels"] for request in github_api.sent("GET", f"/repos/{REPO}/issues")
    }
    assert asked == {"class:security-dep", "class:frontend-dep"}


async def test_no_more_than_the_per_sweep_limit_is_filed(
    scanner_settings: Settings, github_api: FakeAPI, osv_api: FakeAPI
) -> None:
    many = [
        record(
            f"GHSA-{name}",
            package=name,
            ecosystem=audit.NPM,
            events=({"introduced": "0"}, {"fixed": "99.0.0"}),
        )
        for name in ("image-size", "dompurify", "@deck.gl/core", "@deck.gl/mesh-layers", "jest")
    ]

    report = await run_sweep(scanner_settings, github_api, osv_api, records=many)

    assert len(report.filed) == audit.MAX_ISSUES_PER_SWEEP
    assert len(github_api.sent("POST", f"/repos/{REPO}/issues")) == audit.MAX_ISSUES_PER_SWEEP
    assert report.by_reason == {audit.Rejected.OVER_LIMIT: 2}


async def test_a_run_that_finds_nothing_files_nothing(
    scanner_settings: Settings, github_api: FakeAPI, osv_api: FakeAPI
) -> None:
    report = await run_sweep(scanner_settings, github_api, osv_api, records=[])

    assert report.filed == ()
    assert report.skipped == ()
    assert report.scanned == PACKAGES_IN_TREE
    assert github_api.sent("POST", f"/repos/{REPO}/issues") == []


async def test_every_rejection_is_reported_with_its_reason(
    scanner_settings: Settings, github_api: FakeAPI, osv_api: FakeAPI, capture: Any
) -> None:
    logs = capture()

    await run_sweep(scanner_settings, github_api, osv_api, records=ALL_RECORDS)

    events = {entry["event"] for entry in logs.records}
    assert "scanner.sweep.triaged" in events
    skipped = [entry for entry in logs.records if entry["event"] == "scanner.finding.skipped"]
    assert {entry["reason"] for entry in skipped} == {
        "suppressed",
        "build-toolchain",
        "lock-refresh-only",
    }
    filed = [entry for entry in logs.records if entry["event"] == "scanner.issue.filed"]
    assert {entry["issue_class"] for entry in filed} == {"security-dep", "frontend-dep"}
