"""Initial schema: the five tables of docs/03-data-model.md.

Revision ID: d76e40f7bd73
Revises:
Create Date: 2026-08-08 13:51:54.506673

Autogenerated from `sentinel.models` and kept in step with it by the drift test in
`tests/test_models.py`. Constraint and index names come from the naming convention on
`Base.metadata`, which is why they are spelled out through `op.f()` rather than left to Postgres.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d76e40f7bd73"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "acu_ledger",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("acus", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("day", name=op.f("pk_acu_ledger")),
    )
    op.create_table(
        "remediation",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("repo", sa.Text(), nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=False),
        sa.Column("issue_class", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("cycle", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("devin_session_id", sa.Text(), nullable=True),
        sa.Column("devin_session_url", sa.Text(), nullable=True),
        sa.Column("devin_status", sa.Text(), nullable=True),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column("pr_url", sa.Text(), nullable=True),
        sa.Column(
            "acus_consumed",
            sa.Numeric(precision=10, scale=3),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("structured_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("human_message_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("labeled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pr_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ci_green_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_remediation")),
        sa.UniqueConstraint("repo", "issue_number", name=op.f("uq_remediation_repo_issue_number")),
    )
    op.create_index(
        op.f("ix_remediation_devin_session_id"), "remediation", ["devin_session_id"], unique=False
    )
    op.create_index(op.f("ix_remediation_labeled_at"), "remediation", ["labeled_at"], unique=False)
    op.create_index(op.f("ix_remediation_state"), "remediation", ["state"], unique=False)
    op.create_table(
        "webhook_delivery",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("delivery_id", sa.Text(), nullable=False),
        sa.Column("event", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handler_result", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_delivery")),
        sa.UniqueConstraint("delivery_id", name=op.f("uq_webhook_delivery_delivery_id")),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("remediation_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["remediation_id"], ["remediation.id"], name=op.f("fk_job_remediation_id_remediation")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_index(op.f("ix_job_status_run_after"), "job", ["status", "run_after"], unique=False)
    op.create_table(
        "remediation_event",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("remediation_id", sa.BigInteger(), nullable=False),
        sa.Column("webhook_delivery_id", sa.BigInteger(), nullable=True),
        sa.Column("from_state", sa.Text(), nullable=True),
        sa.Column("to_state", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["remediation_id"],
            ["remediation.id"],
            name=op.f("fk_remediation_event_remediation_id_remediation"),
        ),
        sa.ForeignKeyConstraint(
            ["webhook_delivery_id"],
            ["webhook_delivery.id"],
            name=op.f("fk_remediation_event_webhook_delivery_id_webhook_delivery"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_remediation_event")),
    )
    op.create_index(
        op.f("ix_remediation_event_remediation_id_created_at"),
        "remediation_event",
        ["remediation_id", "created_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_remediation_event_remediation_id_created_at"), table_name="remediation_event"
    )
    op.drop_table("remediation_event")
    op.drop_index(op.f("ix_job_status_run_after"), table_name="job")
    op.drop_table("job")
    op.drop_table("webhook_delivery")
    op.drop_index(op.f("ix_remediation_state"), table_name="remediation")
    op.drop_index(op.f("ix_remediation_labeled_at"), table_name="remediation")
    op.drop_index(op.f("ix_remediation_devin_session_id"), table_name="remediation")
    op.drop_table("remediation")
    op.drop_table("acu_ledger")
