#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Generate the ADR index and the path-scoped ADR pointer rule.

Both outputs are derived from the YAML front matter of the files in docs/adr/.
They are generated rather than hand-written because parallel sessions add ADRs
independently, and a hand-maintained index goes stale within days.

    uv run scripts/gen_adr_index.py           # write
    uv run scripts/gen_adr_index.py --check   # fail if the outputs are stale
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ADR_DIR = Path("docs/adr")
INDEX = ADR_DIR / "index.md"
POINTERS = Path(".claude/rules/adr-pointers.md")
EXCLUDED = {"index.md", "template.md"}

REQUIRED_FIELDS = ("title", "status", "date", "type")
GENERATED_NOTE = "<!-- Generated by scripts/gen_adr_index.py. Do not edit by hand. -->"


def load_adrs() -> list[dict]:
    adrs = []
    for path in sorted(ADR_DIR.glob("*.md")):
        if path.name in EXCLUDED:
            continue
        text = path.read_text()
        if not text.startswith("---\n"):
            raise SystemExit(f"{path}: missing YAML front matter")
        _, raw, _ = text.split("---\n", 2)
        meta = yaml.safe_load(raw) or {}
        missing = [f for f in REQUIRED_FIELDS if not meta.get(f)]
        if missing:
            raise SystemExit(f"{path}: front matter missing {', '.join(missing)}")
        meta["slug"] = path.stem
        meta["path"] = path.name
        adrs.append(meta)
    return adrs


def as_list(meta: dict, key: str) -> list[str]:
    value = meta.get(key) or []
    return [str(v) for v in value]


def render_index(adrs: list[dict]) -> str:
    by_date = sorted(adrs, key=lambda a: (str(a["date"]), a["slug"]), reverse=True)

    lines = [
        "# Architecture Decision Records",
        "",
        "> **Status:** Living · **Answers:** Why is it built this way, and what was rejected?",
        "",
        GENERATED_NOTE,
        "",
        "The specs under `docs/` record *what* was decided. These records keep the *why*, and the",
        "options that were considered and dropped, so a later session does not re-litigate a settled",
        "question. See [when to write one](../implementation-plan.md#adrs).",
        "",
        "## By date",
        "",
        "| Date | Decision | Type | Status | Areas |",
        "|---|---|---|---|---|",
    ]
    for a in by_date:
        areas = ", ".join(as_list(a, "areas")) or "—"
        lines.append(
            f"| {a['date']} | [{a['title']}](./{a['path']}) | {a['type']} | {a['status']} | {areas} |"
        )

    by_area: dict[str, list[dict]] = defaultdict(list)
    for a in adrs:
        for area in as_list(a, "areas") or ["general"]:
            by_area[area].append(a)

    lines += ["", "## By area", ""]
    for area in sorted(by_area):
        entries = ", ".join(
            f"[{a['title']}](./{a['path']})"
            for a in sorted(by_area[area], key=lambda x: x["slug"])
        )
        lines.append(f"- **{area}** — {entries}")

    by_task: dict[str, list[dict]] = defaultdict(list)
    for a in adrs:
        for task in as_list(a, "tasks"):
            by_task[task].append(a)

    if by_task:
        lines += [
            "",
            "## By task",
            "",
            "Look up your task id before starting work.",
            "",
            "| Task | Decisions that constrain it |",
            "|---|---|",
        ]
        for task in sorted(by_task):
            entries = ", ".join(
                f"[{a['title']}](./{a['path']})"
                for a in sorted(by_task[task], key=lambda x: x["slug"])
            )
            lines.append(f"| {task} | {entries} |")

    lines.append("")
    return "\n".join(lines)


def render_pointers(adrs: list[dict]) -> str:
    by_file: dict[str, list[dict]] = defaultdict(list)
    for a in adrs:
        for f in as_list(a, "files"):
            by_file[f].append(a)

    paths = sorted(by_file)
    front = ["---", "paths:"]
    front += [f'  - "{p}"' for p in paths] or ['  - "docs/adr/*.md"']
    front.append("---")

    lines = front + [
        "",
        GENERATED_NOTE,
        "",
        "# Decisions that constrain this file",
        "",
        "You are editing a file covered by an existing decision record. Read the linked ADR before",
        "changing the behaviour it describes. If you are deliberately overturning it, supersede the",
        "ADR in the same pull request rather than leaving it contradicted by the code.",
        "",
    ]
    for f in paths:
        entries = ", ".join(
            f"[{a['title']}](../../docs/adr/{a['path']})"
            for a in sorted(by_file[f], key=lambda x: x["slug"])
        )
        lines.append(f"- `{f}` — {entries}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if outputs are stale")
    args = parser.parse_args()

    adrs = load_adrs()
    outputs = {INDEX: render_index(adrs), POINTERS: render_pointers(adrs)}

    stale = [p for p, content in outputs.items() if not p.exists() or p.read_text() != content]
    if args.check:
        if stale:
            print("Stale generated files: " + ", ".join(str(p) for p in stale), file=sys.stderr)
            print("Run: make adr-index", file=sys.stderr)
            return 1
        print(f"ADR index up to date ({len(adrs)} records)")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    print(f"Wrote {INDEX} and {POINTERS} ({len(adrs)} records)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
