#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Generate the ADR index and the path-scoped ADR pointer rule.

Both outputs are derived from the YAML front matter of the files in docs/adr/.
They are generated rather than hand-written because parallel sessions add ADRs
independently, and a hand-maintained index goes stale within days.

Front matter is validated against docs/tasks.yaml first, and nothing is written
unless every record passes. The index is only as trustworthy as the records it
is built from: a mistyped area or task id would otherwise produce an index that
is quietly wrong, which is worse than one that fails to build.

    uv run scripts/gen_adr_index.py           # write
    uv run scripts/gen_adr_index.py --check   # fail if the outputs are stale
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ADR_DIR = Path("docs/adr")
INDEX = ADR_DIR / "index.md"
POINTERS = Path(".claude/rules/adr-pointers.md")
TASKS = Path("docs/tasks.yaml")
EXCLUDED = {"index.md", "template.md"}

FILENAME = re.compile(r"\d{4}-\d{2}-\d{2}-[a-z0-9]+(?:-[a-z0-9]+)*")
REQUIRED_FIELDS = ("title", "status", "date", "type", "areas")
LIST_FIELDS = ("areas", "tasks", "files", "specs")
KNOWN_FIELDS = (*REQUIRED_FIELDS, "tasks", "files", "specs", "supersedes")
STATUSES = ("accepted", "superseded", "deprecated")
TYPES = ("architecture", "process")
GENERATED_NOTE = "<!-- Generated by scripts/gen_adr_index.py. Do not edit by hand. -->"

INDEX_PREAMBLE = """\
The specs under `docs/` record *what* was decided. These records keep the *why*, and the
options that were considered and dropped, so a later session does not re-litigate a settled
question. See [when to write one](../implementation-plan.md#adrs)."""

POINTERS_PREAMBLE = """\
You are editing a file covered by an existing decision record. Read the linked ADR before
changing the behaviour it describes. If you are deliberately overturning it, supersede the
ADR in the same pull request rather than leaving it contradicted by the code."""


def one_line(exc: Exception) -> str:
    """YAML errors span several lines and quote the source; the file is named separately."""
    return " ".join(str(exc).split())


def read_front_matter(path: Path) -> dict:
    """Parse one record. Raises ValueError with a message a human can act on."""
    text = path.read_text()
    if not text.startswith("---\n"):
        raise ValueError("missing YAML front matter")
    parts = text.split("---\n", 2)
    if len(parts) < 3:
        raise ValueError("front matter is never closed by a second ---")
    try:
        meta = yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError as exc:
        raise ValueError(f"front matter is not valid YAML: {one_line(exc)}") from exc
    if not isinstance(meta, dict):
        raise ValueError(f"front matter is a {type(meta).__name__}, expected a mapping of fields")
    return meta


def check_record(path: Path, meta: dict, areas: set[str], task_ids: set[str]) -> list[str]:
    """Everything wrong with one record, so that one run reports them all."""
    problems = []

    def bad(message: str) -> None:
        problems.append(f"{path}: {message}")

    if not FILENAME.fullmatch(path.stem):
        bad("filename is not YYYY-MM-DD-slug.md")

    missing = [f for f in REQUIRED_FIELDS if not meta.get(f)]
    if missing:
        bad(f"front matter is missing or empty: {', '.join(missing)}")

    unknown = sorted(set(meta) - set(KNOWN_FIELDS))
    if unknown:
        bad(
            f"unknown front matter field(s) {', '.join(unknown)} — known: {', '.join(KNOWN_FIELDS)}"
        )

    date = meta.get("date")
    if date is not None:
        if not isinstance(date, dt.date):
            bad(f"date {date!r} is not a YYYY-MM-DD date")
        elif not path.stem.startswith(f"{date}-"):
            bad(f"date {date} disagrees with the filename")

    if (status := meta.get("status")) and status not in STATUSES:
        bad(f"status {status!r} is not one of {', '.join(STATUSES)}")
    if (type_ := meta.get("type")) and type_ not in TYPES:
        bad(f"type {type_!r} is not one of {', '.join(TYPES)}")

    malformed = set()
    for field in LIST_FIELDS:
        value = meta.get(field)
        if value is None:
            continue
        if not isinstance(value, list) or any(not isinstance(v, str) for v in value):
            bad(f"{field} must be a list of strings, got {value!r}")
            malformed.add(field)

    if "areas" not in malformed:
        vocabulary = ", ".join(sorted(areas))
        for area in meta.get("areas") or []:
            if area not in areas:
                bad(f"area {area!r} is not one of the areas in {TASKS}: {vocabulary}")
    if "tasks" not in malformed:
        for task in meta.get("tasks") or []:
            if task not in task_ids:
                bad(f"task {task!r} is not a task in {TASKS}")

    return problems


def check_supersessions(adrs: list[dict]) -> list[str]:
    """A supersession the index cannot render is a decision silently listed twice as live."""
    by_slug = {a["slug"]: a for a in adrs}
    problems = []
    claimed: dict[str, str] = {}

    for adr in sorted(adrs, key=lambda a: a["slug"]):
        target = adr.get("supersedes")
        if not target:
            continue
        where = f"{ADR_DIR / adr['path']}: supersedes {target!r}"
        if not isinstance(target, str):
            problems.append(f"{ADR_DIR / adr['path']}: supersedes must be a slug, got {target!r}")
        elif target == adr["slug"]:
            problems.append(f"{where}, which is itself")
        elif target not in by_slug:
            problems.append(f"{where}, and no record with that slug exists")
        elif by_slug[target]["status"] != "superseded":
            problems.append(
                f"{where}, whose status is still {by_slug[target]['status']!r} — "
                "set it to 'superseded' so the index stops presenting it as live"
            )
        elif target in claimed:
            problems.append(f"{where}, which {claimed[target]} also supersedes")
        else:
            claimed[target] = adr["slug"]

    return problems


def load_vocabulary() -> tuple[set[str], set[str]]:
    """The areas and task ids ADR front matter is allowed to name."""
    if not ADR_DIR.is_dir() or not TASKS.is_file():
        raise SystemExit(
            f"{ADR_DIR} and {TASKS} must both exist — run this from the repository root"
        )
    tasks = yaml.safe_load(TASKS.read_text())
    return set(tasks["areas"]), {t["id"] for t in tasks["tasks"]}


def load_adrs() -> list[dict]:
    areas, task_ids = load_vocabulary()
    adrs: list[dict] = []
    problems: list[str] = []

    for path in sorted(ADR_DIR.glob("*.md")):
        if path.name in EXCLUDED:
            continue
        try:
            meta = read_front_matter(path)
        except ValueError as exc:
            problems.append(f"{path}: {exc}")
            continue
        problems += check_record(path, meta, areas, task_ids)
        meta["slug"] = path.stem
        meta["path"] = path.name
        adrs.append(meta)

    if not adrs and not problems:
        raise SystemExit(f"no decision records found in {ADR_DIR}")
    problems += check_supersessions(adrs)
    if problems:
        raise SystemExit(
            "\n".join(
                [*problems, f"{len(problems)} problem(s) in ADR front matter; nothing written"]
            )
        )
    return adrs


def as_list(meta: dict, key: str) -> list[str]:
    """Validation has already established that these fields are lists of strings."""
    return meta.get(key) or []


def link(adr: dict) -> str:
    return f"[{adr['title']}](./{adr['path']})"


def labelled(adr: dict) -> str:
    """A record that no longer holds is still listed, but never as if it did."""
    suffix = "" if adr["status"] == "accepted" else f" ({adr['status']})"
    return f"{link(adr)}{suffix}"


def render_index(adrs: list[dict]) -> str:
    by_date = sorted(adrs, key=lambda a: (str(a["date"]), a["slug"]), reverse=True)
    replaced_by = {a["supersedes"]: a for a in adrs if a.get("supersedes")}

    lines = [
        "# Architecture Decision Records",
        "",
        "> **Status:** Living · **Answers:** Why is it built this way, and what was rejected?",
        "",
        GENERATED_NOTE,
        "",
        *INDEX_PREAMBLE.splitlines(),
        "",
        "## By date",
        "",
        "| Date | Decision | Type | Status | Areas |",
        "|---|---|---|---|---|",
    ]
    for a in by_date:
        areas = ", ".join(as_list(a, "areas"))
        successor = replaced_by.get(a["slug"])
        status = a["status"] if successor is None else f"{a['status']} → {link(successor)}"
        lines.append(f"| {a['date']} | {link(a)} | {a['type']} | {status} | {areas} |")

    by_area: dict[str, list[dict]] = defaultdict(list)
    for a in adrs:
        for area in as_list(a, "areas"):
            by_area[area].append(a)

    lines += ["", "## By area", ""]
    for area in sorted(by_area):
        entries = ", ".join(labelled(a) for a in sorted(by_area[area], key=lambda x: x["slug"]))
        lines.append(f"- **{area}** — {entries}")

    by_task: dict[str, list[dict]] = defaultdict(list)
    for a in adrs:
        for task in as_list(a, "tasks"):
            by_task[task].append(a)

    if by_task:
        lines += [
            "",
            "## By task",
            "",
            "Look up your task id before starting work.",
            "",
            "| Task | Decisions that constrain it |",
            "|---|---|",
        ]
        for task in sorted(by_task):
            entries = ", ".join(labelled(a) for a in sorted(by_task[task], key=lambda x: x["slug"]))
            lines.append(f"| {task} | {entries} |")

    lines.append("")
    return "\n".join(lines)


def render_pointers(adrs: list[dict]) -> str:
    by_file: dict[str, list[dict]] = defaultdict(list)
    for a in adrs:
        for f in as_list(a, "files"):
            by_file[f].append(a)

    paths = sorted(by_file)
    front = ["---", "paths:"]
    front += [f'  - "{p}"' for p in paths] or ['  - "docs/adr/*.md"']
    front.append("---")

    lines = [
        *front,
        "",
        GENERATED_NOTE,
        "",
        "# Decisions that constrain this file",
        "",
        *POINTERS_PREAMBLE.splitlines(),
        "",
    ]
    for f in paths:
        entries = ", ".join(
            f"[{a['title']}](../../docs/adr/{a['path']})"
            + ("" if a["status"] == "accepted" else f" ({a['status']})")
            for a in sorted(by_file[f], key=lambda x: x["slug"])
        )
        lines.append(f"- `{f}` — {entries}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if outputs are stale")
    args = parser.parse_args()

    adrs = load_adrs()
    outputs = {INDEX: render_index(adrs), POINTERS: render_pointers(adrs)}

    stale = [p for p, content in outputs.items() if not p.exists() or p.read_text() != content]
    if args.check:
        if stale:
            print("Stale generated files: " + ", ".join(str(p) for p in stale), file=sys.stderr)
            print("Run: make adr-index", file=sys.stderr)
            return 1
        print(f"ADR index up to date ({len(adrs)} records)")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    print(f"Wrote {INDEX} and {POINTERS} ({len(adrs)} records)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
